### ISSUE TITLE
Reintroduce scripts to composer install

### ISSUE THREAD

**Issue by bshaffer** [GoogleCloudPlatform/php-docker#135] opened 2016-08-02 17:48 UTC
We added `--no-scripts` to the composer install commmand in https://github.com/GoogleCloudPlatform/php-docker/pull/69. Why did we do this?

This could be a very way for users to run simple pre-deployment tasks (such as changing file permissions, warming up caches, etc) without having to extent the `Dockerfile`. We can add `--no-interaction` to the composer install command, to ensure the build can complete.

@cedricziel

**Comment by tmatsuo** [comment] 2016-08-02 17:56
Yeah we discuss enabling running script with composer, because it is a handy way of doing pre-work before serving the app.

I thought you needed to disable script because symfony's script raises an error.

Can you provide a reproducible app so that we can investigate for workaround solutions?

**Comment by bshaffer** [comment] 2016-08-02 17:59
Symfony Standard uses composer's `post-install-cmd` to generate [`parameters.yml`](https://github.com/symfony/symfony-standard/blob/master/app/config/parameters.yml.dist#L1) (see [here](https://github.com/symfony/symfony-standard/blob/master/composer.json#L37)). Laravel uses `post-install-cmd` to run [`php artisan optimize`](https://github.com/laravel/laravel/blob/master/composer.json#L40).

**Comment by cedricziel** [comment] 2016-08-02 18:31
Long story short:

The `ONBUILD` hook executes at a point in time, where I can do nothing to interfere or fullfill package wise dependencies, such as installing debian packages or building php extensions.

Symfony for example compiles the dependency injection container and compiles proxy classes through the composer script handler which will ultimately result in errors if I can not supply all needed depencies or customize the image to my needs *before* the very first composer script execution.

If you think about enabling the scripts again, please provide a tag that doesnt run them.

To understand a more complex problem, I've written a bunch of comments about my initial intention: Removing the `--no-dev` argument in https://github.com/GoogleCloudPlatform/php-docker/pull/66
The default env with symfony is `dev`. I won't repeat all of that here, but in short, the solution would be to mimic the heroku images in that regard (see #66)

**Comment by tmatsuo** [comment] 2016-08-02 18:41
Ok, so how about this?

* During ONBUILD, run `composer install --no-scripts --no-dev --prefer-dist --optimize-autoloader --no-interaction --no-ansi --no-progress`
* in the `entrypoint.sh` (it's executed at runtime), run the composer again without `--no-scripts`, `composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction --no-ansi --no-progress`

Then you can have your own Dockerfile to modify the env before the 2nd `composer install`. The 2nd `composer install` can see the user defined env vars too.

How does it sound?

**Comment by bshaffer** [comment] 2016-08-02 21:16
you can define arbitrary script groups also. We could define our own, which would allow apps to run the scripts when we wanted them to run, i.e:

```sh
composer run-script post-build-cmd
```

**Comment by cedricziel** [comment] 2016-08-03 09:02
Hmm. All this is very suboptimal. I ran into file permission problems the last time I relied on automatically executed scripts which essentially marked the composer scripts blocking or even harmfull.

Relevant parts from my Dockerfile: (`###ENV_VARIABLES###` is substituted with things like the current revision and other app specifics) 
```
FROM gcr.io/php-mvm-a/php-nginx:latest

ENV DOCUMENT_ROOT /app/web
ENV SYMFONY_ENV prod
ENV PHP_PATH /opt/php/bin/php
ENV SYMFONY_ASSETS_INSTALL hard

### ENV VARIABLES ###

# Supervisor needs a more lax umask for the php-fpm so the applications'
# front controllers don't need to be modified to use the umask() function.
COPY supervisord.conf /etc/supervisor/supervisord.conf

# Change umask so the application can read and write to var dir
RUN sed -i -e 's/^UMASK *[0-9]*.*/UMASK    002/' /etc/login.defs

# Remove all previous caches
RUN rm -Rf /app/var/cache/prod

# Optimize application state by removing unnecessary classes from the
# autoloader
RUN cd $APP_DIR && $PHP_DIR/bin/php \
    -d display_errors=1 \
    -d display_startup_errors=1 \
    -d suhosin.executor.include.whitelist=phar \
    -d suhosin.executor.func.blacklist=none \
    -d disable_functions= \
    -d memory_limit=-1 \
    -d max_input_time=-1 \
    /usr/local/bin/composer \
    install \
    -vvv \
    --prefer-dist \
    --no-dev \
    --optimize-autoloader \
    --no-interaction \
    && $PHP_DIR/bin/php \
    -d display_errors=1 \
    -d display_startup_errors=1 \
    -d suhosin.executor.include.whitelist=phar \
    -d suhosin.executor.func.blacklist=none \
    -d disable_functions= \
    -d memory_limit=-1 \
    -d max_input_time=-1 \
    bin/console assetic:dump \
    && rm -Rf /app/var/cache/prod

# Reset rights
RUN chown -R www-data:www-data /app
RUN find /app/var -type f -exec chmod 660 {} \;
RUN find /app/var -type d -exec chmod 750 {} \;
```

I remember discussing file permissions in the issues. My point is that being able to read, write and delete files is one of the competitive advantages opposed to AppEngine Standard. Someone raised security concerns about that and insisted on locking everything down to 55* with both having the file modes set permanently and keeping the umask strict.

Why do I mention this? Running the composer scripts or `install` in the entrypoint would mark all my efforts from above with making the relevant parts writable useless without adding a once again custom composer script to the json file.

I'm very sorry if I appear reluctant, but this caused real pain for a very simple application.

**Comment by tmatsuo** [comment] 2016-08-03 18:24
Thanks for the Dockerfile @cedricziel 

Re: file permissions
`/tmp` directory is writable. Isn't it possible to use that directory?

Re: composer script
I need to think more about it, but thanks for the actual exemple!

**Comment by cedricziel** [comment] 2016-08-04 14:57
@tmatsuo

re: scripts: yeah, the scripts stuff is hard to crack, since it affects everyone, anytime and I can only speak for myself. - I also thought of having sort of a "barebones" docker tag fo the image where no composer stuff is actually done and everything's customizable. Just like the original PHP images, we could have  `php:7`, `php:7-no-scripts` etc. But that's just an idea. I think the existing configuration options are already [relatively] complex.

re: permissions: Using `/tmp` is always possible, but... the umask thing. the composer scripts run as root and fpm runs as `www-data` which can't modify anything. Neither stuff in the app directory, nor things that are generated to /tmp by script runs. So I could say it depends where the files originate.

**Comment by tmatsuo** [comment] 2016-08-04 17:25
@cedricziel 
re: permissions

Oh yes, very good pint. `root` and `www-data`! I think we should run composer as www-data. I hope this change will simplify things a bit.

**Comment by tmatsuo** [comment] 2016-08-09 23:00
https://github.com/GoogleCloudPlatform/php-docker/pull/138 is merged.

**Closed** 2016-08-09 23:43 UTC
